export const CONTACT_US_NAME_INPUT_CHANGED = 'CONTACT_US_NAME_INPUT_CHANGED'
export const CONTACT_US_EMAIL_INPUT_CHANGED = 'CONTACT_US_EMAIL_INPUT_CHANGED'
export const CONTACT_US_SUBJECT_INPUT_CHANGED = 'CONTACT_US_SUBJECT_INPUT_CHANGED'
export const CONTACT_US_EMAIL_CONTENT_INPUT_CHANGED = 'CONTACT_US_EMAIL_CONTENT_INPUT_CHANGED'

export const FORM_SUBMITTED = 'FORM_SUBMITTED'

